name:               "Electric Seance"
description:        "A narrative-driven spirit board experience"

url:                ""
author:             "konahart"
email:              "eseance@konahart.com"
twitter:            "konahart"
github:             "konahart/electric-seance"

disqus_shortname:   "konahart"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

background-image:   bg.jpg

rel-nav:
  - name:           "Demos"
    href:           "demos"
  - name:           "About"
    href:           "about"

abs-nav:
  - name:           "Download"
    href:           "https://github.com/konahart/Electric-Seance"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
